### ISSUE TITLE
results are shaking

### ISSUE THREAD

**Issue by ChenFengYe** [wangsen1312/joints2smpl#1]
Hi, thanks for your work. This is quite useful code.
However, I find the results are shaking. Even the results from [test_motion2.npy](https://github.com/wangsen1312/joints2smpl/blob/main/demo/demo_data/test_motion2.npy)

Is there any params I haven't adjusted? any hints?

**Comment by wangsen1312** [comment]
@ChenFengYe  If the joint position is not the key metric, you can try some smooth filters among the sequences, such as Gaussian filter.
