### ISSUE TITLE
gmm = pickle.load(f, encoding='latin1') 

### ISSUE THREAD

**Issue by NourCheikh** [wangsen1312/joints2smpl#15]
hello @wangsen1312  thank you for your amazing work 

I need help with this error that I got recently when I tried to run this command python fit_seq.py --files test_motion2.npy

gmm = pickle.load(f, encoding='latin1') _pickle.UnpicklingError: the STRING opcode argument must be quoted

I have no clue on how to solve it. I hope you can help me !! Thank You !!

**Comment by Ancolie18** [comment]
Hi, I also meet is error, how do you solve it? Thanks!!

**Comment by wangsen1312** [comment]
@Ancolie18 Could you show the error? please make sure the pickle is original lib~

**Comment by Ancolie18** [comment]
> @Ancolie18 Could you show the error? please make sure the pickle is original lib~

Thanks for your reply! The pkl file that cannot be loaded is joints2smpl \ SMPL_models \ gmm08.pkl. What do you mean"original lib"?  and there is no problem with this code. I have tried to load other pkl files. Perhaps it is a problem with this file?

Namespace(batchSize=1, cuda=True, data_folder='./demo/demo_data/', files='test_motion2.npy', fix_foot='False', gpu_ids=0, joint_category='AMASS', num_joints=22, num_smplify_iters=100, save_folder='./demo/demo_results/')
./smpl_models/
Traceback (most recent call last):
  File "fit_seq.py", line 63, in <module>
    smplify = SMPLify3D(smplxmodel=smplmodel,
  File "src\smplify.py", line 67, in __init__
    self.pose_prior = MaxMixturePrior(prior_folder=config.GMM_MODEL_DIR,
  File "src\prior.py", line 127, in __init__
    gmm = pickle.load(f, encoding='latin1')
_pickle.UnpicklingError: the STRING opcode argument must be quoted

**Comment by Ancolie18** [comment]
I modified the code in prior.py, now can run the code:

        # # original code (line 127)
        # with open(full_gmm_fn, 'rb') as f:
        #     gmm = pickle.load(f, encoding='latin1')   
            
        original = "./smpl_models/gmm_08.pkl"
        destination = "./smpl_models/gmm_08_win10.pkl"
        content = ''
        outsize = 0
        with open(original, 'rb') as infile:            
            content = infile.read()
        with open(destination, 'wb') as output:
            
            for line in content.splitlines():
                outsize += len(line) + 1
                output.write(line + str.encode('\n'))
        print("Done. Saved %s bytes." % (len(content)-outsize))

        # ./smpl_models/gmm_{:02d}.pkl
        with open(destination, 'rb') as f:
            gmm = pickle.load(f, encoding='latin1')   
            
in demo_results folder, these files are generated.
![image](https://github.com/user-attachments/assets/2bf099fb-01ab-4b25-9d29-20d0f0c1521b)
I tried to load pkl file, but meet an error:
file = pickle.load(f, encoding='latin1')
_pickle.UnpicklingError: invalid load key, 'x'.

the generated pkl file should be opened by joblib.load()

path3 = "./demo/demo_results/test_motion2/0002.pkl"
file = joblib.load(open(path3, 'rb'))  #加载

I found that the speed of generating results is not fast. Is there any way to improve the speed? Do you have more learning materials for this open source project or method~？
