### ISSUE TITLE
Human3.6 Data for smpl fitting

### ISSUE THREAD

**Issue by Dipankar1997161** [wangsen1312/joints2smpl#5]
Hello @wangsen1312,

I was wondering which datasets was it trained on ?

I wish to generate smpl parameters from 3d joints of Human3.6m as thats my research part. I tried few,  but the results weren't accurate for reconstruction

If you have any files or h36m(smpl parameters), do let me know.

**Comment by Lyman-Smoker** [comment]
Hi, 

I also meet the same problem. 

Have you solved this problem yet?

Thanks

**Comment by Dipankar1997161** [comment]
> Hi,
> 
> I also meet the same problem.
> 
> Have you solved this problem yet?
> 
> Thanks

Yes. I solved the problem using EasyMocap but I updated the pipeline a bit to use the GT keypoints of Human3.6 m instead of Predicted ones from openpose or Hr-net

**Comment by CodesChangeHair** [comment]
I encountered the same issue. Could you share the code you used to solve the problem? @Dipankar1997161
