### ISSUE TITLE
May I ask the corresponding map of the 22 joint keypoints in the demo file

### ISSUE THREAD

**Issue by snowmint** [wangsen1312/joints2smpl#7]
My original generated body joints have 34 keypoints, now I use very simple way to mapping the body joint to SMPL 24 joint ( in (x, y, z) coordinate system), I'm struggling on how to turn the 3D keypoints into SMPL model, then I found this repository.
But when I look down into demo program, and try to apply my body joints, found there need 22 keypoints (like test_motion2.npy).
May I ask the corresponding map of the 22 joint keypoints in the demo file?
Thank you.

**Comment by wangsen1312** [comment]
@snowmint You can try to change the src/config.py file. You can mapping the joints one by one. Please let me know whether it can solve the problem.

**Comment by snowmint** [comment]
> @snowmint You can try to change the src/config.py file. You can mapping the joints one by one. Please let me know whether it can solve the problem.

Thank for your quick reply, after modify the config file it transform correctly!
Very appreciate your advice!
