### ISSUE TITLE
May I ask is there a way to apply custom textures to the SMPL model?

### ISSUE THREAD

**Issue by snowmint** [wangsen1312/joints2smpl#8]
I have managed to transform the body pose coordinates to the SMPL (.ply) file using the codes you provided in the repo. However, I wasn’t able to apply my customized textures using Blender. I tried to modify your codes but to no avail. I would like to know if you have any advice on how to texture SMPL models.

Here is the link to the video showcasing the transformed SMPL model:
https://drive.google.com/file/d/1TWwpYr1wkAHH8TSR1ICcJCo60LYV5UF8/view?usp=sharing

 I used Texformer (from another repo) to transform the single image to the SMPL textures:
![uvmap_test_1_1](https://github.com/wangsen1312/joints2smpl/assets/7868828/98f5d757-f8f0-49c2-84c3-ffdb153afe4e)
![uvmap_photo_test5](https://github.com/wangsen1312/joints2smpl/assets/7868828/12a8deae-f59f-4738-92bf-f9f64a565470)

Hope there is a way to apply the texture on the SMPL model to get even more realistic visualization.

Thank you.

**Comment by dancasas** [comment]
Hi, you can grab the UV coordinates from any SMPL obj mesh that has texture coordinates, for example here

https://github.com/dancasas/SMPLitex/blob/main/sample-data/smpl_uv_20200910/smpl_uv.obj

Just copy and paste the lines starting with `f` and `vt` (which define the UV coordinates) into your SMPL obj, and it should work. 

You can grab new textures from our new dataset https://dancasas.github.io/projects/SMPLitex/SMPLitex-dataset.html
